# docker-compose.yml
version: "3.9"
services:
  # Servicio de la app Django
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app # monta el código en tiempo real
    ports:
      - "8000:8000"
    env_file:
      - .env # variables de entorno
    depends_on:
      - db
  # Servicio de PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # Servicio de pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

    # Construir las imágenes
    # ----- docker compose build
    # Levantar todos los servicios
    # ----- docker compose up
    # Levantar en segundo plano (detached)
    # ----- docker compose up -d
    # Ver logs del servicio web
    # ----- docker compose logs -f web
    # Ejecutar un comando dentro del contenedor
    # ----- docker compose exec web python manage.py migrate
    # Apagar todos los servicios
    # ----- docker compose down


# migrar django
# --- docker compose exec web python manage.py showmigrations
# --- docker compose exec web python manage.py migrate
# superusuario
# --- docker compose exec web python manage.py createsuperuser

# postgresql
# --- docker exec -it django_web_db psql -U postgres
# --- docker exec -it django-encomiendas--laboratorio-sesion-02--db-1 psql -U postgres