# docker-compose.yml
version: "3.9"
services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis # <- el servicio web depende de Redis
    environment:
      - REDIS_URL=redis://redis:6379/1
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  # Servicio de pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # Servicio de Redis (Caché / Throttling)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" # exponer para conectar con redis-cli local
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf # configuracion
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  redis_data: # <- volumen persistente para Redis
  pgadmin_data:
