# Generated by Django 6.0.4 on 2026-04-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volumen_cm3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_est', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente')),
                ('empleado_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'db_table': 'encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2)),
                ('estado_nuevo', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='envios.empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda')),
            ],
            options={
                'db_table': 'historial_estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
