# Generated by Django 6.0.4 on 2026-05-02 16:18

import django.core.validators
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso mínimo es 0.01 kg')]),
        ),
    ]
