"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "clientes",
    "rutas",
    "envios",
    # Nuevas librerías de API (agregar estas 4 líneas) <-- NUEVO
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",
    "corsheaders",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # <-- NUEVO: debe ir PRIMERO
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # sirve archivos estáticos en producción
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # <- carpeta global de templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # processor personalizado:
                "envios.context_processors.estadisticas_globales",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE"),
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# ── Configuración de Caché (Redis) ───────────────────────────────
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CACHE_TTL = 60 * 15  # 15 minutos por defecto


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-pe"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# URL base para los archivos estaticos
STATIC_URL = "static/"
# Carpetas donde Django busca los archivos en DESARROLLO
STATICFILES_DIRS = [
    BASE_DIR / "static",  # <- aqui pones tus CSS, JS, imagenes
]
# Carpeta donde se juntan todos al hacer collectstatic (PRODUCCION)
STATIC_ROOT = BASE_DIR / "staticfiles"
# Archivos subidos por el usuario (formularios con FileField/ImageField)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# Configuración de Sesiones
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 horas
SESSION_COOKIE_SECURE = False  # Cambiar a True en producción con HTTPS
SESSION_COOKIE_NAME = "encomiendas_session"


# ── JWT: configuración de tokens ──────────────────────────────────

SIMPLE_JWT = {
    # Token expira en 1 hora
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    # Refresh expira en 7 días
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Rotar el refresh token en cada uso
    "ROTATE_REFRESH_TOKENS": True,
    # Authorization: Bearer <token>
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ── CORS: permitir peticiones desde el frontend ───────────────────

CORS_ALLOW_ALL_ORIGINS = True  # En desarrollo

# En producción reemplazar por:
# CORS_ALLOWED_ORIGINS = [
#     'https://tu-frontend.com'
# ]

# ── Documentación de la API ───────────────────────────────────────

SPECTACULAR_SETTINGS = {
    # ── Metadatos principales ────────────────────────────────────
    "TITLE": "API Sistema de Gestión de Encomiendas",
    "DESCRIPTION": """
    API REST para gestionar el ciclo de vida de encomiendas.

    Incluye:
    - Registro de envíos
    - Cambio de estado
    - Historial de movimientos
    - Estadísticas del sistema
    """,
    "VERSION": "1.0.0",
    # ── Configuración visual/documentación ───────────────────────
    # No mostrar el schema JSON en Swagger UI
    "SERVE_INCLUDE_SCHEMA": False,
    # Separar schemas request/response
    "COMPONENT_SPLIT_REQUEST": True,
    # Mantener el orden del router
    "SORT_OPERATIONS": False,
    # ── Tags agrupados en Swagger ────────────────────────────────
    "TAGS": [
        {
            "name": "Encomiendas",
            "description": "Gestión de envíos",
        },
        {
            "name": "Clientes",
            "description": "Listado de clientes activos",
        },
        {
            "name": "Rutas",
            "description": "Rutas disponibles",
        },
        {
            "name": "Auth",
            "description": "Autenticación JWT",
        },
    ],
}

# ── Configuración Global Django REST Framework ──────────────────

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "api.exceptions.encomiendas_exception_handler",
    # ── Autenticación ────────────────────────────────────────────
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # ── Permisos ─────────────────────────────────────────────────
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # ── Throttling / Rate Limiting ───────────────────────────────
    "DEFAULT_THROTTLE_CLASSES": [
        # Usuarios anónimos
        "rest_framework.throttling.AnonRateThrottle",
        # Usuarios autenticados
        "rest_framework.throttling.UserRateThrottle",
    ],
    # ── Rate limits ──────────────────────────────────────────────
    "DEFAULT_THROTTLE_RATES": {
        # Usuarios anónimos
        "anon": "20/hour",
        # Usuarios autenticados
        "user": "500/hour",
        # Empleados autenticados
        "empleado": "100/min",
        # Cambio de estado
        "cambio_estado": "30/hour",
        # Login
        "login_attempt": "5/min",
    },
    # ── Paginación ───────────────────────────────────────────────
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 15,
    # ── OpenAPI / Swagger ────────────────────────────────────────
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # ── Versionado de API ────────────────────────────────────────
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # Versiones permitidas
    "ALLOWED_VERSIONS": [
        "v1",
        "v2",
    ],
    # Versión por defecto
    "DEFAULT_VERSION": "v1",
    # Nombre del parámetro de versión
    "VERSION_PARAM": "version",
}


# ────────────────────────────────────────────────────────────────
# CORS (Cross-Origin Resource Sharing)
# ────────────────────────────────────────────────────────────────

# ── Desarrollo ──────────────────────────────────────────────────
#
# Permitir cualquier origen
# SOLO usar en desarrollo
#

CORS_ALLOW_ALL_ORIGINS = True


# ── Producción ──────────────────────────────────────────────────
#
# Reemplazar configuración anterior en producción
#

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    # Frontend producción
    "https://encomiendas-frontend.vercel.app",
    # Panel admin
    "https://admin.encomiendas.pe",
    # React local
    "http://localhost:3000",
    # Vite local
    "http://localhost:5173",
]

# ── Permitir cookies JWT HttpOnly ───────────────────────────────

CORS_ALLOW_CREDENTIALS = True

# ── Headers permitidos ──────────────────────────────────────────

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-requested-with",
]

# ── Métodos HTTP permitidos ─────────────────────────────────────

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


# ── Configuración para Django Silk (Performance Profiler) ─────────
# Agregar solo si DEBUG = True

if DEBUG:
    INSTALLED_APPS += ["silk"]
    MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]
    SILKY_PYTHON_PROFILER = True
    SILKY_META = True  # mostrar queries de silk en el panel
